
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: trazabilidad_documentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cenyt123*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 aplicacion_documentos.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8081:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY='django-insecure-wht0eh&-@+fkqqz19=_klgp*-^vv$iz7sz$p3+sv6i##+1h&!'
      - DB_NAME=trazabilidad_documentos
      - DB_USER=postgres
      - DB_PASSWORD=Cenyt123*
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
