# Generated by Django 5.1.5 on 2025-01-14 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_actual', models.CharField(default='VIGENTE', max_length=50)),
                ('etapa_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('version_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_version', models.IntegerField(blank=True, null=True)),
                ('estado_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_actual', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_evento', models.DateTimeField(auto_now_add=True)),
                ('estado_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('etapa_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('version_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_version', models.IntegerField(blank=True, null=True)),
                ('estado_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_evento', to=settings.AUTH_USER_MODEL)),
                ('usuario_interesado_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_interesado_1', to=settings.AUTH_USER_MODEL)),
                ('usuario_interesado_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_interesado_2', to=settings.AUTH_USER_MODEL)),
                ('usuario_interesado_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_interesado_3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='subproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.subproyecto'),
        ),
    ]
