# Generated by Django 5.1.5 on 2025-02-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_estado_actual_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Solicitud_Superación_Numero_de_Versión',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='Solicitud_Superación_de_Versión',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='Solicitud_de_Envio',
            field=models.BooleanField(default=False),
        ),
    ]
