# Generated by Django 5.1.5 on 2025-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documento_solicitud_superación_numero_de_versión_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado_actual',
            field=models.CharField(default='NUEVO ', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='etapa_actual',
            field=models.CharField(blank=True, default='PRELIMINAR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero_version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='version_actual',
            field=models.CharField(blank=True, default='A', max_length=50, null=True),
        ),
    ]
