# Generated by Django 5.1.5 on 2025-03-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_estado_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
