# Generated by Django 5.1.5 on 2025-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documento_codigo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo_cliente',
            field=models.CharField(blank=True, default='Sin Código', max_length=100, null=True),
        ),
    ]
