# Generated by Django 5.1.5 on 2025-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documento_codigo_cliente_evento_correos_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
