# Generated by Django 5.1.5 on 2025-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_alter_documento_codigo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='usuario_interesado_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
