# Generated by Django 5.1.5 on 2025-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_alter_documento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='codigo_cliente',
            field=models.CharField(blank=True, default='Sin Código', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ruta_actual',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ruta_actual',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(max_length=200),
        ),
    ]
