# Generated by Django 5.1.5 on 2025-03-03 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_alter_evento_usuario_interesado_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='codigo_cliente',
        ),
        migrations.AlterField(
            model_name='evento',
            name='usuario_interesado_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_interesado_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
