# Generated by Django 5.1.5 on 2025-03-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_remove_documento_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='codigo_cliente',
            field=models.CharField(blank=True, default='Sin Código', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='correos_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado_actual',
            field=models.CharField(default='NUEVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='etapa_actual',
            field=models.CharField(blank=True, default='NUEVO', max_length=50, null=True),
        ),
    ]
